ServerEvents.tags("item", r => {
    r.add(
        'create_nouveau:stripped_archwood',
        [
            'ars_nouveau:stripped_blue_archwood_log',
            'ars_nouveau:stripped_blue_archwood_wood',
            'ars_nouveau:stripped_green_archwood_log',
            'ars_nouveau:stripped_green_archwood_wood',
            'ars_nouveau:stripped_red_archwood_log',
            'ars_nouveau:stripped_red_archwood_wood',
            'ars_nouveau:stripped_purple_archwood_log',
            'ars_nouveau:stripped_purple_archwood_wood',
            'ars_elemental:stripped_yellow_archwood_log',
            'ars_elemental:stripped_yellow_archwood'
        ])
    r.add('create:casing', [
        'create_nouveau:magic_casing',
        'create_nouveau:source_casing',
        'create_nouveau:smartcasing'
    ])
    r.add(
        'create_nouveau:rope_materials',
        [
            'supplementaries:flax',
            'farmersdelight:straw'
        ]
    )
    r.add(
        'hexcasting:dusts/amethyst',
        [
            'ars_technica:amethyst_dust'
        ]
    )
    r.add(
        'hexcasting:grants_root_advancement',
        [
            'ars_technica:amethyst_dust'
        ]
    )
    r.add(
        'tconstruct:anvil_metal',
        [
            "anvilcraft:royal_steel_block",
            "anvilcraft:ember_metal_block",
            "anvilcraft:polished_heavy_iron_block",
            "anvilcraft:cursed_gold_block",
            "anvilcraft:earth_core_shard_block"
        ]
    )
})