ServerEvents.recipes(r => {
    const handcraft = r.recipes.create.item_application
    handcraft(
        "create_nouveau:magic_casing",
        [
            "#create_nouveau:stripped_archwood",
            "#forge:ingots/enchanted_gold"
        ]
    )
    handcraft(
        'create_nouveau:smart_andesite_casing',
        ['create:andesite_casing',
            'create:electron_tube']
    )
    handcraft(
        'create_nouveau:smart_andesite_casing',
        ['create:andesite_casing',
            'create_nouveau:crude_electron_tube']
    )
    handcraft(
        'ars_nouveau:source_jar',
        [
            "create_nouveau:magic_casing",
            '#forge:glass_panes'
        ]
    )
    handcraft(
        'create:item_vault',
        [
            'create:andesite_casing',
            'create_nouveau:storage_unit'
        ]
    )
    handcraft(
        'create:fluid_tank',
        [
            'create:copper_casing',
            'create_nouveau:storage_unit'
        ]
    )
    handcraft(
        'railways:fuel_tank',
        [
            'create:railway_casing',
            'create_nouveau:storage_unit'
        ]
    )
    handcraft(
        'create:cogwheel',
        ['create:shaft',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create:large_cogwheel',
        ['create:shaft',
            'extendedgears:large_shaftless_cogwheel']
    )
    handcraft(
        'create:cogwheel',
        ['extendedgears:shaftless_cogwheel',
            'create:shaft']
    )
    handcraft(
        'create:large_cogwheel',
        ['extendedgears:large_shaftless_cogwheel',
            'create:shaft']
    )
    handcraft(
        'create_basic_additions:basic_gearshift',
        ['create:andesite_casing',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create:clutch',
        ['create_basic_additions:basic_gearshift',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:andesite_t-gearbox',
        ['create:clutch',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create:gearbox',
        ['create_basic_additions:andesite_t-gearbox',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_connected:parallel_gearbox',
        ['create:gearbox',
            'extendedgears:large_shaftless_cogwheel']
    )
    handcraft(
        'create_connected:six_way_gearbox',
        ['create_connected:parallel_gearbox',
            'extendedgears:large_shaftless_cogwheel']
    )
    handcraft(
        'create:gearshift',
        ['create_basic_additions:basic_gearshift',
            'minecraft:redstone']
    )
    handcraft(
        'ars_nouveau:imbuement_chamber',
        ['create_nouveau:magic_casing',
            '#forge:plates/gold']
    )
    handcraft(
        'ars_nouveau:relay',
        ['create_nouveau:magic_casing',
            'ars_nouveau:source_gem_block']
    )
    handcraft(
        'ars_nouveau:spell_prism',
        ['create_nouveau:magic_casing',
            '#forge:storage_blocks/quartz']
    )
    handcraft(
        'ars_elemental:advanced_prism',
        ['ars_nouveau:spell_prism',
            'ars_nouveau:source_gem']
    )
    handcraft(
        'create_nouveau:smart_casing',
        ['create:brass_casing',
            'create:electron_tube']
    )
    handcraft(
        'create:mechanical_pump',
        [
            'create:fluid_pipe',
            'extendedgears:shaftless_cogwheel'
        ]
    )
    handcraft(
        'create:smart_chute',
        ['create_nouveau:smart_casing',
            'create:chute']
    )
    handcraft(
        'create:content_observer',
        ['create_nouveau:smart_casing',
            'minecraft:observer']
    )
    handcraft(
        'create:stockpile_switch',
        ['create_nouveau:smart_casing',
            'minecraft:comparator']
    )
    handcraft(
        'supplementaries:stone_lamp',
        ['minecraft:stone',
            'minecraft:glowstone_dust']
    )
    handcraft(
        'supplementaries:blackstone_lamp',
        ['minecraft:blackstone',
            'minecraft:glowstone_dust']
    )
    handcraft(
        'supplementaries:deepslate_lamp',
        ['minecraft:deepslate',
            'minecraft:glowstone_dust']
    )
    handcraft(
        'supplementaries:end_stone_lamp',
        ['minecraft:end_stone',
            'minecraft:glowstone_dust']
    )
    handcraft(
        'create_nouveau:source_casing',
        ['create_nouveau:magic_casing',
            'create_nouveau:enchantment_mechanism']
    )
    handcraft(
        'create:encased_chain_drive',
        ['create:andesite_casing',
            'create_nouveau:chain_drive']
    )
    handcraft(
        'create:sequenced_gearshift',
        ['create_nouveau:smart_casing',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create:empty_blaze_burner',
        ['minecraft:netherrack',
            'create_nouveau:cage']
    )
    handcraft(
        'create_connected:empty_fan_catalyst',
        ['create:brass_casing',
            'create_nouveau:cage']
    )
    handcraft(
        'create:mechanical_press',
        ['create:andesite_casing',
            'minecraft:iron_block']
    )
    handcraft(
        'create:mechanical_mixer',
        ['create_basic_additions:basic_gearshift',
            'create:whisk']
    )
    handcraft(
        'create:mechanical_saw',
        ['create:andesite_casing',
            'create_nouveau:saw']
    )
    handcraft(
        'create:encased_fan',
        ['create:andesite_casing',
            'create:propeller']
    )
    handcraft(
        'create:portable_storage_interface',
        ['create:andesite_casing',
            'create_nouveau:storage_connector']
    )
    handcraft(
        'create:portable_fluid_interface',
        ['create:copper_casing',
            'create_nouveau:storage_connector']
    )
    handcraft(
        'railways:portable_fuel_interface',
        ['create:railway_casing',
            'create_nouveau:storage_connector']
    )
    handcraft(
        'create_connected:inventory_access_port',
        ['create_nouveau:smart_casing',
            'create_nouveau:storage_connector']
    )
    handcraft(
        'create:turntable',
        ['#minecraft:wooden_slabs',
            'create:shaft']
    )
    handcraft(
        'create:windmill_bearing',
        ['#forge:stone',
            'create:turntable']
    )
    handcraft(
        'create:mechanical_bearing',
        ['create:andesite_casing',
            'create:turntable']
    )
    handcraft(
        'create:clockwork_bearing',
        ['create_nouveau:smart_casing',
            'create:turntable']
    )
    handcraft(
        'create:piston_extension_pole',
        ['create:shaft',
            'tconstruct:pattern']
    )
    handcraft(
        'ars_nouveau:enchanting_apparatus',
        ['create_nouveau:source_casing',
            'minecraft:diamond']
    )
    handcraft(
        'ars_nouveau:arcane_pedestal',
        ['create_nouveau:source_casing',
            'ars_nouveau:sourcestone']
    )
    handcraft(
        'ars_nouveau:arcane_core',
        ['ars_nouveau:sourcestone',
            'create_nouveau:enchantment_mechanism']
    )
    handcraft(
        'ars_nouveau:ritual_brazier',
        ['create_nouveau:source_casing',
            'ars_nouveau:source_gem_block']
    )
    handcraft(
        'create:mechanical_piston',
        ['create:andesite_casing',
            'create:piston_extension_pole']
    )
    handcraft(
        'create:basin',
        ['minecraft:cauldron',
            'create:andesite_alloy']
    )
    handcraft(
        'create:depot',
        ['create:andesite_casing',
            'create:andesite_alloy']
    )
    handcraft(
        'create:millstone',
        ['create_basic_additions:basic_gearshift',
            '#forge:stone']
    )
    handcraft(
        'create:rotation_speed_controller',
        ['create:brass_casing',
            'create:precision_mechanism']
    )
    handcraft(
        'create:mechanical_arm',
        ['create:rotation_speed_controller',
            'create:brass_hand']
    )
    handcraft(
        'create:spout',
        ['create:copper_casing',
            'minecraft:dried_kelp']
    )
    handcraft(
        'create_enchantment_industry:printer',
        ['create:spout',
            '#forge:plates/iron']
    )
    handcraft(
        'create:adjustable_chain_gearshift',
        ['create_nouveau:smart_andesite_casing',
            'create_nouveau:chain_drive']
    )
    handcraft(
        'create:deployer',
        ['create_nouveau:smart_andesite_casing',
            'create:brass_hand']
    )
    handcraft(
        'starbunclemania:fluid_jar',
        ['create_nouveau:magic_casing',
            'create_nouveau:storage_unit']
    )
    handcraft(
        'ars_nouveau:mob_jar',
        ['create_nouveau:magic_casing',
            '#forge:glass']
    )
    handcraft(
        'starbunclemania:source_condenser',
        ['ars_nouveau:relay',
            'starbunclemania:fluid_jar']
    )
    handcraft(
        'create:mechanical_roller',
        ['create_nouveau:smart_andesite_casing',
            'create:crushing_wheel']
    )
    handcraft(
        'create:item_drain',
        ['create:copper_casing',
            'minecraft:iron_bars']
    )
    handcraft(
        'create_enchantment_industry:disenchanter',
        ['create:copper_casing',
            '#create:sandpaper']
    )
    handcraft(
        'create_nouveau:electric_casing',
        ['create:brass_casing',
            'createaddition:capacitor']
    )
    handcraft(
        'createaddition:portable_energy_interface',
        ['create_nouveau:electric_casing',
            'create_nouveau:storage_connector']
    )
    handcraft(
        'createaddition:modular_accumulator',
        ['create_nouveau:electric_casing',
            'create_nouveau:storage_unit']
    )
    handcraft(
        'create:speedometer',
        ['create:andesite_casing',
            'minecraft:compass']
    )
    handcraft(
        'create:cuckoo_clock',
        ['create:andesite_casing',
            'minecraft:clock']
    )
    handcraft(
        'create:mechanical_drill',
        ['create:andesite_casing',
            'create_nouveau:drill']
    )
    handcraft(
        'create_basic_additions:basic_copper_gearshift',
        ['create:copper_casing',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:copper_clutch',
        ['create_basic_additions:basic_copper_gearshift',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:copper_t-gearbox',
        ['create_basic_additions:copper_clutch',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:copper_gearbox',
        ['create_basic_additions:copper_t-gearbox',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:copper_gearshift',
        ['create_basic_additions:basic_copper_gearshift',
            'minecraft:redstone']
    )
    handcraft(
        'create_basic_additions:basic_brass_gearshift',
        ['create:brass_casing',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:brass_clutch',
        ['create_basic_additions:basic_brass_gearshift',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:brass_t-gearbox',
        ['create_basic_additions:brass_clutch',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:brass_gearbox',
        ['create_basic_additions:brass_t-gearbox',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:brass_gearshift',
        ['create_basic_additions:basic_brass_gearshift',
            'minecraft:redstone']
    )
    handcraft(
        'create_connected:brass_gearbox',
        ['create_basic_additions:brass_gearbox',
            'create:precision_mechanism']
    )
    handcraft(
        'create_basic_additions:basic_railway_gearshift',
        ['create:railway_casing',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:railway_clutch',
        ['create_basic_additions:basic_railway_gearshift',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:railway_t-gearbox',
        ['create_basic_additions:railway_clutch',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:railway_gearbox',
        ['create_basic_additions:railway_t-gearbox',
            'extendedgears:shaftless_cogwheel']
    )
    handcraft(
        'create_basic_additions:railway_gearshift',
        ['create_basic_additions:basic_railway_gearshift',
            'minecraft:redstone']
    )
    handcraft(
        'create_connected:freewheel_clutch',
        ['create:clutch',
            '#forge:plates/iron']
    )
    handcraft(
        'create_connected:centrifugal_clutch',
        ['create_connected:freewheel_clutch',
            'create:flywheel']
    )
    handcraft(
        'create_connected:overstress_clutch',
        ['create_connected:freewheel_clutch',
            'create:electron_tube']
    )
    const logs = [
        "oak",
        "spruce",
        "birch",
        "jungle",
        "acacia",
        "dark_oak",
        "mangrove",
        "cherry"
    ]
    logs.forEach(wood => {
        let log = `minecraft:${wood}_log`
        let staff = `hexcasting:staff/${wood}`
        handcraft(
            staff,
            [log,
                'hexcasting:charged_amethyst']
        )
    })
    handcraft(
        'hexcasting:staff/crimson',
        ['minecraft:crimson_stem',
            'hexcasting:charged_amethyst']
    )
    handcraft(
        'hexcasting:staff/warped',
        ['minecraft:warped_stem',
            'hexcasting:charged_amethyst']
    )
    handcraft(
        'hexcasting:staff/bamboo',
        ['minecraft:bamboo_block',
            'hexcasting:charged_amethyst']
    )
    handcraft(
        'hexcasting:staff/edified',
        ['hexcasting:edified_log',
            'hexcasting:charged_amethyst']
    )
    handcraft(
        'minecraft:spawner',
        ['ars_additions:source_spawner',
            'tconstruct:blaze_head']
    )
    handcraft(
        'anvilcraft:magnetoelectric_core',
        ['create_nouveau:copper_wire',
            'anvilcraft:hollow_magnet_block']
    )
    handcraft(
        'create:fluid_valve',
        [
            'create:fluid_pipe',
            'minecraft:heavy_weighted_pressure_plate'
        ]
    )
    handcraft(
        'create:smart_fluid_pipe',
        [
            'create:fluid_pipe',
            'create_connected:control_chip'
        ]
    )
})
