ServerEvents.recipes(r=>{
    const ars_nouveau = r.recipes.ars_nouveau
    ars_nouveau.imbuement(
        'create:polished_rose_quartz', // input item
        'create_nouveau:enchanted_rose_quartz', // output
        1000, // source cost
        []
    );
    ars_nouveau.enchanting_apparatus(
        [
            "minecraft:stick",
            'minecraft:oak_planks',
        ], // input items
	    "hexcasting:charged_amethyst", // reagent
	    "hexcasting:staff/oak", // output
	    1000, // source cost
	    // true // keep nbt of reagent, think like a smithing recipe
	);
    ars_nouveau.enchanting_apparatus(
        [
            'minecraft:spruce_planks',
            'minecraft:stick',
        ],
        "hexcasting:charged_amethyst",
        "hexcasting:staff/spruce",
        1000
    );
    ars_nouveau.enchanting_apparatus(
        [
            'minecraft:birch_planks',
            'minecraft:stick',
        ],
        "hexcasting:charged_amethyst",
        'hexcasting:staff/birch',
        1000
    );
    ars_nouveau.enchanting_apparatus(
        [
            'minecraft:acacia_planks',
            'minecraft:stick',
        ],
        "hexcasting:charged_amethyst",
        'hexcasting:staff/acacia',
        1000
    ); ars_nouveau.enchanting_apparatus(
        [
            'minecraft:spruce_planks',
            'minecraft:stick',
        ],
        "hexcasting:charged_amethyst",
        "hexcasting:staff/spruce",
        1000
    );
    ars_nouveau.enchanting_apparatus(
        [
            'minecraft:dark_oak_planks',
            'minecraft:stick',
        ],
        "hexcasting:charged_amethyst",
        'hexcasting:staff/dark_oak',
        1000
    );
    ars_nouveau.enchanting_apparatus(
        [
            'minecraft:crimson_planks',
            'minecraft:stick',
        ],
        "hexcasting:charged_amethyst",
        'hexcasting:staff/crimson',
        1000
    );
    ars_nouveau.enchanting_apparatus(
        [
            'minecraft:warped_planks',
            'minecraft:stick',
        ],
        "hexcasting:charged_amethyst",
        'hexcasting:staff/warped',
        1000
    );
    ars_nouveau.enchanting_apparatus(
        [
            'minecraft:mangrove_planks',
            'minecraft:stick',
        ],
        "hexcasting:charged_amethyst",
        'hexcasting:staff/mangrove',
        1000
    );
    ars_nouveau.enchanting_apparatus(
        [
            'minecraft:jungle_planks',
            'minecraft:stick',
        ],
        "hexcasting:charged_amethyst",
        'hexcasting:staff/jungle',
        1000
    );
    ars_nouveau.enchanting_apparatus(
        [
            'minecraft:cherry_planks',
            'minecraft:stick',
        ],
        "hexcasting:charged_amethyst",
        'hexcasting:staff/cherry',
        1000
    );
    ars_nouveau.enchanting_apparatus(
        [
            'minecraft:bamboo_planks',
            'minecraft:stick',
        ],
        "hexcasting:charged_amethyst",
        'hexcasting:staff/bamboo',
        1000
    );
    ars_nouveau.enchanting_apparatus(
        [
            'hexcasting:edified_planks',
            'minecraft:stick',
        ],
        "hexcasting:charged_amethyst",
        'hexcasting:staff/edified',
        1000
    );
    ars_nouveau.enchanting_apparatus(
        [
            'hexcasting:quenched_allay_shard',
            'hexcasting:quenched_allay_shard',
            'hexcasting:quenched_allay_shard',
            'minecraft:grindstone'
        ],
        '#hexcasting:staves',
        'hexcasting:staff/quenched',
        2000,
    );
    ars_nouveau.imbuement(
        '#hexcasting:staves',
        'hexcasting:staff/mindsplice',
        2000,
        [
            'minecraft:grindstone',
            '#hexcasting:brainswept_circle_components',
        ]
    )
})