StartupEvents.registry("block", r => {
    r.create("create_nouveau:magic_casing", "basic")
        .woodSoundType()
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/axe")
        .tagBlock("minecraft:mineable/pickaxe")
    r.create("create_nouveau:source_casing", "basic")
        .soundType(SoundType.METAL)
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
    r.create("create_nouveau:smart_casing", "basic")
        .soundType(SoundType.METAL)
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
    r.create("create_nouveau:smart_andesite_casing", "basic")
        .stoneSoundType()
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
    r.create("create_nouveau:electric_casing", "basic")
        .soundType(SoundType.METAL)
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
    r.create("create_nouveau:copper_wire", "basic")
        .soundType(SoundType.METAL)
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
        .tagBlock('forge:need_iron_tool')
        .tagBlock('forge:storage_blocks/steel')
        .tagBlock('minecraft:beacon_base_blocks')
        .tagBlock('tconstruct:mineable/pickadze')
    r.create("create_nouveau:steel_block", "basic")
        .soundType(SoundType.METAL)
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
        .tagBlock('forge:need_iron_tool')
        .tagBlock('forge:storage_blocks/steel')
        .tagBlock('minecraft:beacon_base_blocks')
        .tagBlock('tconstruct:mineable/pickadze')
    r.create("create_nouveau:enchanted_gold_block", "basic")
        .soundType(SoundType.METAL)
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
        .tagBlock('forge:need_iron_tool')
        .tagBlock('forge:storage_blocks/enchanted_gold')
        .tagBlock('minecraft:beacon_base_blocks')
        .tagBlock('tconstruct:mineable/pickadze')
        .item(egb => {
            egb
                .glow(true)
        })
    r.create('create_nouveau:silver_ore')
        .soundType(SoundType.STONE)
        .hardness(3)
        .resistance(3)
        .tag("forge:ores")
        .tag('forge:ores/silver')
        .tag("forge:ore_rates/dense")
        .tagBlock("minecraft:mineable/pickaxe")
        .tagBlock('forge:need_stone_tool')
        .requiresTool(true)
    r.create('create_nouveau:steel_pressure_plate', 'pressure_plate')
        .item(item => {
            item
                .tag("forge:plates/steel")
        })
})