StartupEvents.registry("block", r => {
    r.create("create_nouveau:magic_casing", "basic")
        .woodSoundType()
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/axe")
        .tagBlock("minecraft:mineable/pickaxe")
    r.create("create_nouveau:source_casing", "basic")
        .soundType(SoundType.METAL)
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
    r.create("create_nouveau:smart_casing", "basic")
        .soundType(SoundType.METAL)
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
    r.create("create_nouveau:smart_andesite_casing", "basic")
        .stoneSoundType()
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
    r.create("create_nouveau:electric_casing", "basic")
        .soundType(SoundType.METAL)
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
    r.create("create_nouveau:steel_block", "basic")
        .soundType(SoundType.METAL)
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
        .tagBlock('forge:need_iron_tool')
        .tagBlock('forge:storage_blocks/steel')
        .tagBlock('minecraft:beacon_base_blocks')
        .tagBlock('tconstruct:mineable/pickadze')
})