StartupEvents.registry("block", r => {
    r.create("create_nouveau:magic_casing", "basic")
        .woodSoundType()
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/axe")
        .tagBlock("minecraft:mineable/pickaxe")
    r.create("create_nouveau:source_casing", "basic")
        .stoneSoundType()
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
    r.create("create_nouveau:smart_casing", "basic")
        .stoneSoundType()
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
        r.create("create_nouveau:smart_andesite_casing", "basic")
        .stoneSoundType()
        .hardness(3)
        .requiresTool(true)
        .tagBlock("minecraft:mineable/pickaxe")
})