StartupEvents.registry("item", r => {
    r.create('create_nouveau:chain_drive')
    r.create("create_nouveau:cage")
    r.create("create_nouveau:enchanted_rose_quartz")
    r.create("create_nouveau:storage_unit")
    r.create("create_nouveau:storage_connector")
    r.create("create_nouveau:saw")
    r.create("create_nouveau:ejector_mechanism")
    r.create("create_nouveau:drill")
    r.create('create_nouveau:advanced_circuit_board')
    r.create('create_nouveau:incomplete_enchantment_mechanism', "create:sequenced_assembly")
    r.create('create_nouveau:incomplete_electron_tube', "create:sequenced_assembly")
    r.create('create_nouveau:incomplete_capacitor', 'create:sequenced_assembly')
    r.create('create_nouveau:incomplete_magic_capacitor', 'create:sequenced_assembly')
    r.create('create_nouveau:incomplete_circuit_board', "create:sequenced_assembly")
    r.create('create_nouveau:incomplete_advanced_circuit_board', 'create:sequenced_assembly')
    r.create('create_nouveau:incomplete_electric_burner', 'create:sequenced_assembly')
    r.create('create_nouveau:pineapple_peel_gloves')
        .maxDamage(100)
})