StartupEvents.registry("item", r => {
    r.create('the_magical_industry:enchanted_gold_ingot')
        .glow(true)
        .tag('forge:ingots/enchanted_gold')
    r.create('the_magical_industry:enchanted_gold_nugget')
        .glow(true)
        .tag("forge:nuggets.enchanted_gold")
    r.create('the_magical_industry:magic_capacitor')
    r.create('the_magical_industry:enchantment_mechanism')
    r.create('the_magical_industry:solder_wire')
    r.create('the_magical_industry:solder_coil')
    r.create('the_magical_industry:iron_coil')
    r.create('the_magical_industry:incomplete_enchantment_mechanism', "create:sequenced_assembly")
    r.create('the_magical_industry:incomplete_electron_tube', "create:sequenced_assembly")
    r.create('the_magical_industry:incomplete_capacitor', 'create:sequenced_assembly')
    r.create('the_magical_industry:incomplete_magic_capacitor', 'create:sequenced_assembly')
    r.create('the_magical_industry:incomplete_circuit_board', "create:sequenced_assembly")
    r.create('the_magical_industry:incomplete_advanced_circuit_board', 'create:sequenced_assembly')
    r.create('the_magical_industry:incomplete_electric_burner', 'create:sequenced_assembly')
    r.create('the_magical_industry:incomplete_notor_gizmo', "create:sequenced_assembly")
    r.create('the_magical_industry:incomplete_fissile_core', "create:sequenced_assembly")
})