StartupEvents.registry("sound_event", r => {
    r.create("the_magical_industry:music.cfrb")
    r.create("the_magical_industry:music.life")
    r.create("the_magical_industry:music.evilris")
    r.create("the_magical_industry:music.muisiki_rekuiemu")
})
StartupEvents.registry("item", r => {
    r.create("the_magical_industry:music_disc_life", "music_disc")
        .song("the_magical_industry:music.life", 215)
        .tag("music_discs")
    r.create("the_magical_industry:music_disc_cfrb", "music_disc")
        .song("the_magical_industry:music.cfrb", 167)
        .tag("music_discs")
    r.create("the_magical_industry:music_disc_evilris", "music_disc")
        .song("the_magical_industry:music.evilris", 142)
        .tag("music_discs")
    r.create("the_magical_industry:music_disc_muisiki_rekuiemu", "music_disc")
        .song("the_magical_industry:music.muisiki_rekuiemu", 276)
        .tag("music_discs")
})