StartupEvents.registry("item", r => {
    r.create("the_magical_industry:key_of_dissociation")
        .tag("forge:tools/wrench")
        .tag("forge:tools/key")
        .unstackable()
    r.create("the_magical_industry:debug_tool")
        .tag("the_magical_industry:debug_tool")
    r.create("the_magical_industry:soldering_gun")
    r.create('the_magical_industry:pineapple_peel_gloves')
        .maxDamage(100)
})