StartupEvents.registry("item", r => {
    r.create("create_nouveau:key_of_dissociation")
        .tag("forge:tools/wrench")
        .tag("forge:tools/key")
        .unstackable()
    r.create("create_nouveau:debug_tool")
        .tag("create_nouveau:debug_tool")
    r.create("create_nouveau:soldering_gun")
    r.create('create_nouveau:pineapple_peel_gloves')
        .maxDamage(100)
})