StartupEvents.registry("item", r => {
    r.create("the_magical_industry:key_of_dissociation")
        .tag("forge:tools/wrench")
        .tag("forge:tools/key")
        .unstackable()
    r.create("the_magical_industry:debug_tool")
    .unstackable()
    r.create("the_magical_industry:geological_hammer")
    .unstackable()
    .modifyAttribute('minecraft:generic.attack_damage','minecraft:generic.attack_damage',114514,'addition')
    r.create("the_magical_industry:soldering_gun")
    r.create('the_magical_industry:pineapple_peel_gloves')
        .maxDamage(100)
})