ServerEvents.recipes((event) => {
    let { create } = event.recipes
    create.item_application(
        "create:mechanical_saw",
        [
            "create:andesite_casing",
            Item.of("tconstruct:large_plate", "{Material:'tconstruct:iron'}").strongNBT()
        ]
    ).id("create:crafting/kinetics/mechanical_saw")
    create.item_application(
        "createnuclear:reactor_casing",
        [
            "the_magical_industry:steel_casing",
            "#forge:plates/lead"
        ]
    ).id("createnuclear:item_application/reactor_casing_from_steel_and_brass_casing")
    create.item_application(
        "the_magical_industry:smart_andesite_casing",
        [
            "create:andesite_casing",
            "create:electron_tube"
        ]
    )
    create.item_application(
        "the_magical_industry:smart_andesite_casing",
        [
            "create:andesite_casing",
            "the_magical_industry:crude_electron_tube"
        ]
    )
    create.item_application(
        "the_magical_industry:magic_casing",
        [
            "#the_magical_industry:stripped_archwood",
            "#forge:ingots/enchanted_gold"
        ]
    )
    create.item_application(
        "the_magical_industry:shaftless_cogwheel",
        [
            "#minecraft:wooden_slabs",
            "tinkers_things:chisel"
        ]
    )
        .keepHeldItem()
    create.item_application(
        "the_magical_industry:shaftless_large_cogwheel",
        [
            "#minecraft:planks",
            "tinkers_things:chisel"
        ]
    )
        .keepHeldItem()
    create.item_application(
        "create:cogwheel",
        [
            "create:shaft",
            "the_magical_industry:shaftless_cogwheel"
        ]
    )
        .id("create:crafting/kinetics/cogwheel")
    create.item_application(
        "create:large_cogwheel",
        [
            "create:shaft",
            "the_magical_industry:shaftless_large_cogwheel"
        ]
    )
        .id("create:crafting/kinetics/large_cogwheel")
})