ServerEvents.recipes((event) => {
    let { create } = event.recipes
    create.item_application("createnuclear:reactor_casing",["the_magical_industry:steel_casing","#forge:plates/lead"])
    .id("createnuclear:item_application/reactor_casing_from_steel_and_brass_casing")
    create.item_application("the_magical_industry:smart_andesite_casing",["create:andesite_casing", "create:electron_tube"])
    create.item_application("the_magical_industry:smart_andesite_casing",["create:andesite_casing","the_magical_industry:crude_electron_tube"])
    .id("create:smart_casing_crude")
    create.item_application("the_magical_industry:magic_casing",["#the_magical_industry:stripped_archwood","#forge:ingots/enchanted_gold"])
    create.item_application("the_magical_industry:shaftless_cogwheel",["#minecraft:wooden_slabs","tinkers_things:chisel"])
    .keepHeldItem()
    create.item_application("the_magical_industry:shaftless_large_cogwheel",["#minecraft:planks", "tinkers_things:chisel"])
    .keepHeldItem()
    create.item_application("create:cogwheel",["create:shaft","the_magical_industry:shaftless_cogwheel"])
    .id("create:crafting/kinetics/cogwheel")
    create.item_application("create:large_cogwheel",["create:shaft","the_magical_industry:shaftless_large_cogwheel"])
    .id("create:crafting/kinetics/large_cogwheel")
    //create.item_application(,[,])
    create.item_application("create:deployer",["the_magical_industry:smart_andesite_casing","create:brass_hand"])
    .id("ic:deployer")
    create.item_application('create:mechanical_drill',['create:andesite_casing','the_magical_industry:drill'])
    create.item_application('create:mechanical_mixer',['create:andesite_casing','create:whisk'])
    create.item_application('create:mechanical_press',['create:andesite_casing','minecraft:iron_block'])
    create.item_application('create:encased_fan',['create:andesite_casing','create:propeller'])
    create.item_application('create:mechanical_saw',['create:andesite_casing','the_magical_industry:saw'])
    .id("create:crafting/kinetics/mechanical_saw")
    create.item_application('create:encased_chain_drive',['create:andesite_casing','the_magical_industry:chain_drive'])
    create.item_application('create:millstone',['create:andesite_casing','#forge:stone'])
    create.item_application('create:adjustable_chain_gearshift',['the_magical_industry:smart_andesite_casing','create:chain_drive'])
    create.item_application('create:weighted_ejector',['create:andesite_casing','the_magical_industry:ejector_mechanism'])
})  