StartupEvents.registry("item", r => {
    r.create("the_magical_industry:debug_tool")
        .unstackable()
        .rarity("epic")
    r.create("the_magical_industry:geological_hammer")
        .unstackable()
        .rarity("epic")
    r.create("the_magical_industry:soldering_gun")
        .unstackable()
    r.create("the_magical_industry:pineapple_peel_gloves")
        .unstackable()
        .maxDamage(100)
    r.create("the_magical_industry:key_of_dissociation")
        .unstackable()
        .tag("forge:tools/wrench")
        .tag("forge:tools/key")
})